name: PItemMenu
author: Plancke
main: nl.plancke.pitemmenu.PItemMenu
version: 1.2.2
website: http://www.plancke.nl

commands:
   menu:
      description: Base command.
      usage: /<command> <action>
   menu open:
      description: Open Menu's.
      usage: /<command> <menu>
   menu admin:
      description: Administer the Plugin.
      usage: /<command> <action>